apiVersion: v1
kind: Service
metadata:
  name: recipebook
spec:
  selector:
    app: recipebook
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8080
      nodePort: 30111
  type: LoadBalancer