apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "yourpassword"

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-svc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-svc
  template:
    metadata:
      labels:
        app: movie-svc
    spec:
      containers:
      - name: movie-svc
        image: movie-svc:latest  # Update this line with the correct image
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: movie-svc-service
spec:
  selector:
    app: movie-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
