apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: your-docker-repo/todo:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "your-database-url"